### ISSUE TITLE
Incorrect Charge Amount

### ISSUE THREAD

**Issue by tuppers360** [stripe-samples/react-elements-card-payment#1]
Hi when using your code, it works great however the amount charged in the end process is incorrect as the amount is not converted to the lowest denomination of the currency.

The amount needs to be multiplied by 100 from what I have read in the documentation.

Hope this helps.

Thanks

**Comment by adreyfus-stripe** [comment]
Thanks for reporting! Fixed here: https://github.com/stripe-samples/react-elements-card-payment/pull/3
