### ISSUE TITLE
Error in java start command and 500 error while retrieving payment intents

### ISSUE THREAD

**Issue by kopax** [stripe-samples/react-elements-card-payment#12]
I want to have a working sample of a java server with react stripe.

I did:

```
stripe samples create react-elements-card-payment
# choose java server
mvn pacakge
SPARK_LOCAL_IP=0.0.0.0 java -cp target/react-1.0.0-SNAPSHOT-jar-with-dependencies.jar com.stripe.sample.Server
```

Afterward, I start the client with

```
cd client
yarn
yarn start
```

When I reach the page on http://localhost:3000, I have the following error 500:

```
om.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 26 path $.payment_method_types
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at com.stripe.sample.Server.lambda$main$3(Server.java:88)
```

The client is sending a post request with an array of payment method, while the server expect a string,

I changed https://github.com/stripe-samples/react-elements-card-payment/blob/master/server/java/src/main/java/com/stripe/sample/Server.java#L43

With a `List<String>`, after that, the error is gone and I have a new error two lines after:

```
[qtp998684067-17] ERROR spark.http.matching.GeneralError - 
com.stripe.exception.InvalidRequestException: No such PaymentMethod: card; code: resource_missing; request-id: req_Sj58q2xnBltBcq
	at com.stripe.net.LiveStripeResponseGetter.handleApiError(LiveStripeResponseGetter.java:742)
	at com.stripe.net.LiveStripeResponseGetter.staticRequest(LiveStripeResponseGetter.java:533)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:81)
```

There's obviously an error, is it the client request or the java server?

How can I get the java example and the react work together?

**Comment by auchenberg-stripe** [comment]
Hi @kopax 

Sorry about that. I've pushed a fix. We don't need to pass `payment_methods_types` as the default value is `card` needed for this example.

Please pull master, and you should hopefully be unblocked.

/k

**Comment by kopax** [comment]
@auchenberg-stripe you don't need to but other examples are.

For this reason, (the node version is merging those arguments), you just made those demo servers different.
