### ISSUE TITLE
500 error from Flask on create-payment-intent

### ISSUE THREAD

**Issue by jreich218** [stripe-samples/react-elements-card-payment#16]
Hi,

I installed the project with Flask... and when I got to http://localhost:3000/launch on the frontend I got this error:

<img width="691" alt="Screen Shot 2020-07-07 at 5 46 26 PM" src="https://user-images.githubusercontent.com/22607604/86860491-ce1ffc80-c079-11ea-9ce3-aaa489f88690.png">

Is this a bug or did I make a mistake in the install?

Thanks!
Jason

**Comment by cjavilla-stripe** [comment]
Thanks for reporting @jreich218! Looks like toruf-stripe already has a PR up :)
