### ISSUE TITLE
Demo shows Invalid Host Header

### ISSUE THREAD

**Issue by lack-of-gravitas** [stripe-samples/react-elements-card-payment#17]
# Bug report

## Describe the bug

Clicking on the provided demo link shows Code Sandbox deployed url with a simple Invalid Host Header message. The Code Sandbox project / container also produces the same issue.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'provided demo link: https://rl6zb.sse.codesandbox.io/
2. See error on page load
3. Browser developer console empty, DOM empty (except for above rendered text)

## Expected behavior

Demo application to be loaded as deployed.

## System information

- OS: Ubuntu 20.04
- Browser (if applies) firefox and safari
- Server environment N/A

**Comment by thorsten-stripe** [comment]
I believe this has been resolved by the CodeSandbox team.
