### ISSUE TITLE
Unable to process Payment

### ISSUE THREAD

**Issue by nehawankar174** [stripe-samples/react-elements-card-payment#6]
Hi, I have git cloned the repository and followed the given steps for client and server(node). also specified the keys in **.env** file. When I started application and processed for payment, it is throwing the following error: 
_Invalid PaymentIntent client secret passed to handleCardPayment. Expected string, got undefined._

Attached the screenshot for the same.
![payment](https://user-images.githubusercontent.com/39078864/70801403-d01c2880-1dd4-11ea-855e-45fc5db532f8.PNG)

Any help regarding this.

Thanks!

**Comment by adreyfus-stripe** [comment]
@nehawankar174 Hi! I was able to reproduce by running the server without a properly set up .env file. Did you copy the .env.example file to a file named .env in the same directory as the server and update with your Stripe API keys?

**Comment by nehawankar174** [comment]
Hi!
Thanks, now it works for me. I think there was some issue with my .env file. Now it is working fine.

Thanks once again :)
